language: node_js
node_js:
  - '16.14'

jobs:
  include:
    - stage: test
      name: 'Unit Tests'
      script: 'npm run test'
    - stage: lint
        name: 'Eslint'
        script: 'npm run lint'
    - stage: deploy
      script: 'npm run build'
      name: 'Deploy to NPM'
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        cleanup: true
        on:
          branch: master